### PR TITLE
[ci skip] Get more Open Source Helpers

### PR DESCRIPTION
**Pull request by schneems**
[CodeTriage](https://www.codetriage.com/) is an app I have maintained
for the past 4-5 years with the goal of getting people involved in
Open Source projects like this one. The app sends subscribers a random
open issue for them to help "triage". For some languages you can also
suggested areas to add documentation.

The initial approach was inspired by seeing the work of the small
core team spending countless hours asking "what version was
this in" and "can you give us an example app". The idea is to
outsource these small interactions to a huge team of volunteers
and let the core team focus on their work.

I want to add a badge to the README of this project. The idea is to
provide an easy link for people to get started contributing to this
project. A badge indicates the number of people currently subscribed
to help the repo. The color is based off of open issues in the project.

Here are some examples of other projects that have a badge in their
README:

- https://github.com/crystal-lang/crystal
- https://github.com/rails/rails
- https://github.com/codetriage/codetriage

Thanks for building open source software, I would love to help you find some helpers.

### CODE REVIEW

**Comment by ninabreznik** [comment]
Hey, thanks for this, sorry for late response, I missed it somehow. Sounds like a good project you are doing. Let's see how it works :)

**Comment by schneems** [comment]
Thanks! Let me know if you’ve got any questions or issues.

**Comment by ninabreznik** [comment]
Maybe you can just help me with a quick summary of what I need to do? So I added this badge and now if I create any issues it will automagically add them to CodeTriage or do I have to create an account there and link my repo somehow? Thanks!

**Comment by schneems** [comment]
There's nothing you need to explicitly do. Just try to be welcoming and guiding to new people who start commenting on issues. As issues show up, they'll be mailed out to subscribers on CodeTriage.

If you subscribe to the repo on CodeTriage, you can leave a personalized message that people see when they're subscribed to the repo (since you're the owner). We might add more features for maintainers in the future, but for now that's all we've got.

I personally subscribe to a lot of my own repos and it helps me find issues that I forgot about or went stale.

The app is all open source http://github.com/codetriage/codetriage if you've got any ideas or feature suggestions to help out maintainers, i'm all ears.

**Pull request merged**
